title: Danny Hinojosa # your name (or website title) here
logo: "/images/92608321.jfif?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  From a structural engineering background, I am shifting into the Data Science field to broaden my horizons with the larger picture of how companies thrive. I am committed to help reveal insights for organizations using my technical skills and keen problem-solving instinct. 
  <br><br>
  
  <br><br>
  <a href="https://linkedin.com/in/dannyhinojosa/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
